= Bean Deployment Language (BDL) File Server Sample

A simple File Server using Java built-in Http Server.

I have used http://netbeans.org/[netbeans IDE] for build.

execute the `run` command. 

See the `bdl` directory for the dependency injection.

== BDL (Bean Deployment Language) Files

Inside the `bdl` Dir, *.bdl files are Bean Deployment Language (BDL), used for assembling the Java classes, using Inversion of Control design pattern.

I designed BDL, before 2001, when Spring Framework was still evolving, and Basic Language flavours, like Visual Basic, Star Office Basic were still being used. My development team had inhibition to use Java. BDL has been battle tested many times in production environments, including SMSC Enterprise Gateways in Enterprise and Banks.  

BDL is has a minimalist design and loosely follows the Java Beans Getter/Setter Reflection model.

BDL is a declarative syntax with only 8 Keywords:

* REM (also `;`)      : are comments
* OBJECT              : Instantiate an Object from a Class
* WITH and END WITH   : Delimits the SET Blocks
* SET                 : Calls the `setter` method of a class.               
* RUN                 : Executes a `Runnable` object in a separate `Thread`

. Example Bean Deployment Language (BDL) File, see `prop-test.bdl`
----
REM Save Property to XML test

OBJECT prop AS java.util.Properties

; test if "dots" allowed by BDL parser
WITH prop
   SET Location.latitude = 20
END WITH

OBJECT x2p AS in.innomon.test.Prop2Xml
WITH x2p
    SET prop = prop
    
END WITH

RUN x2p
----

BDL is implemented by the two classes inside the `twister/system` dir.

